CREATE TABLE users (
userId INT IDENTITY(1,1) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
phone VARCHAR(8) UNIQUE NOT NULL,
dob DATE NOT NULL,
password VARCHAR(255) NOT NULL,
preferredLanguage VARCHAR(20) DEFAULT 'English',
role VARCHAR(20) );