CREATE TABLE users (
userId INT IDENTITY(1,1) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
phone VARCHAR(8) UNIQUE NOT NULL,
dob DATE NOT NULL,
password VARCHAR(255) NOT NULL,
preferredLanguage VARCHAR(20) DEFAULT 'English',
role VARCHAR(20) );

CREATE TABLE events (
eventId INT IDENTITY(1,1) PRIMARY KEY,
header VARCHAR(100) NOT NULL,
intro VARCHAR(1000) NOT NULL,
location VARCHAR(50) NOT NULL,
time DateTime NOT NULL,
)